version: '3'

services:
  backend:
    build: .
    container_name: rembg-backend
    volumes:
      - ./app:/app/app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - rembg-network
    # Expose port explicitly to host for debugging
    ports:
      - "5000:5000"

  frontend:
    image: nginx:alpine
    container_name: rembg-frontend
    ports:
      - "81:80"
    volumes:
      - ./app/templates:/usr/share/nginx/html
      - ./app/static:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rembg-network
      
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: rembg-pocketbase-new
    volumes:
      - pocketbase_data_new:/pb_data
    restart: unless-stopped
    ports:
      - "8090:8090"
    networks:
      - rembg-network

networks:
  rembg-network:
    driver: bridge

volumes:
  pocketbase_data_new: 