version: '3'

services:
  backend:
    build: .
    container_name: rembg-backend
    volumes:
      - ./app:/app/app
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: rembg-frontend
    ports:
      - "80:80"
    volumes:
      - ./app/templates:/usr/share/nginx/html
      - ./app/static:/usr/share/nginx/html/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: unless-stopped 